services:
  airflow:
    build:
      context: ..
      dockerfile: docker/airflow/Dockerfile
    profiles: ["orchestration", "full"]
    container_name: finlake-airflow
    #restart: unless-stopped
    command: standalone
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_metadata
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_ADMIN_USER:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    ports:
      - "${AIRFLOW_PORT:-8080}:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../data:/opt/airflow/data
    networks:
      - finlake-net
    depends_on:
      postgres:
        condition: service_healthy
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
    #  start_period: 60s